### ISSUE TITLE
Issues with harmony

### ISSUE THREAD

**Issue by simonh1000** [orchestrate-io/orchestrate.js#107]
I've had to switch off using harmony with 0.12.7 as I ended up with an error that _key was not defined in caseless.

This is how I launch my server script with the commented out command as the part that failed with Orchestrate (rest of my app runs fine)

```
gulp.task('serve', function(){
	return nodemon({
		script: 'index.js',
		// execMap: {
	    //   js: "node --harmony --use_strict"
	    // },
	    watch: 'server/*',
		env: config
	});
});
```

**Comment by housejester** [comment]
Hi Simon. We just pushed a new version 0.5.0 to address this. It just updates the dependencies and seemed to fix the issue for me locally. Please let us know if this did not fix the issue for you. Thanks.
