### ISSUE TITLE
[TypeError: Cannot read property 'length' of undefined]

### ISSUE THREAD

**Issue by Jorenm** [orchestrate-io/orchestrate.js#114]
I'm getting the above error in my fail callback when doing searches on one of my collections. Doesn't seem to matter what I search for. For example:

db.search('events', 'value.id:d5f0e83e-e60e-4316-a9d5-3f6170a70286')

If I perform the same search through the dashboard, it works fine.

**Comment by benjismith** [comment]
Can you post a more complete example, showing how you process the callback? It's difficult to see what the problem might be without seeing a bit more of the context.

**Comment by Jorenm** [comment]
Well, I don't know what was going on, but I came back to it this morning and it stopped doing it.
