### ISSUE TITLE
Return more parsed metadata

### ISSUE THREAD

**Issue by tkazec** [orchestrate-io/orchestrate.js#72]
Example: create a new event. The response object does contain the ref, timestamp, and ordinal... but hidden away in the unparsed headers. The client should parse these for the developer.

**Comment by housejester** [comment]
This was addressed in #90 . For any write request, if the response includes the Location header, the 'Path Metadata' will be parsed from the Location header and provided as 'path' on the result. For example:

```javascript
db.post("testing", {"test":"test"})
  .then(function(result){
    console.log(result.path.key)
  });
```
