### ISSUE TITLE
Error on newGraphReader when offset(0)

### ISSUE THREAD

**Issue by raugaral** [orchestrate-io/orchestrate.js#82]
I am usind the version 0.3.15.
I have in a database only 1 element, and I create a newGraphReader for search this.
If create a newGraphReader with offset(0), return an error:
{ [AssertionError: Offset required.]
  name: 'AssertionError',
  actual: 0,
  expected: true,
  operator: '==',
  message: 'Offset required.' }
If create a newGraphReader with offset(1), not return the element...

What can I do for resolving this??
pd: I need the always the offset attribute.

**Comment by ketanbhatt** [comment]
or do an 
.offset(String(0))

Confirmed working because I just used it and was just going to submit an Issue for it when I saw yours.

**Comment by sjkaliski** [comment]
Node's `assert` lib throws on 0. Fixing now.
