### ISSUE TITLE
"The requested application is setup in a different datacenter."

### ISSUE THREAD

**Issue by simonh1000** [orchestrate-io/orchestrate.js#83]
So ends my first experiment with Orchestrate!?! :-(

Using Node.js

**Comment by housejester** [comment]
Hi Simon. Were you unable to configure the client to use the EU DC?  The instructions are at the link in the error message:
https://orchestrate.io/docs/multi-data-center

For the node client:
```javascript
var oio = require('orchestrate')
oio.ApiEndPoint = "api.aws-eu-west-1.orchestrate.io"
var client = oio('API KEY')
// check the API is reachable and the API key is valid
client.ping()
  .fail(function (err) {
    // invalid API key or API unreachable
  });

```

**Comment by simonh1000** [comment]
That worked - I was just following the code in readme.md. Might be worth adding the above to that

**Comment by housejester** [comment]
Cool. I'll keep this open until we do so. Thanks.

**Comment by jeevan-kr** [comment]
Thanks, this helped me too!
