### ISSUE TITLE
db.post() should return the generated key

### ISSUE THREAD

**Issue by hnordt** [orchestrate-io/orchestrate.js#91]
Hello.

It would be very nice if db.post() returns the generated key:

```javascript
db.post("collection", { payload: true }).then(function (result) {
    reply(result.body); // result.body at the moment is always null
});
```

**Comment by housejester** [comment]
The latest release addresses this, though we should probably document it better :) For all write operations, you can access the "path metadata" under result.path. So, for your example:

```javascript
db.post("collection", { payload: true }).then(function (result) {
    reply(result.path.key); // reply with the generated key
});
```

**Comment by hnordt** [comment]
Thank you so much my friend!
